wiremock:
  server:
    port: 9999

group-manager:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

expense-manager:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

payment-manager:
  url: http://localhost:${wiremock.server.port}
  read-timeout: 1000ms
  connect-timeout: 1000ms

server:
  shutdown: immediate

spring:
  main:
    allow-bean-definition-overriding: true

reconciliation-job-executor:
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 3

reconciliation-job-producer:
  corePoolSize: 1
  maxPoolSize: 1
  queueCapacity: 1

reconciliation-job-processor:
  enabled: true
  lockTime: 10s
  emptyCandidateDelay: 10s
  retryDelays:
    - 0s
