
resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []
    groupManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableGroupManagerClientException
      ignoreExceptions: []
    expenseManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryableExpenseManagerClientException
      ignoreExceptions: [ ]
    paymentManager:
      maxAttempts: 3
      waitDuration: 100ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - pl.edu.agh.gem.internal.client.RetryablePaymentManagerClientException
      ignoreExceptions: [ ]

group-manager:
  url: "group/manager/some/url"
  read-timeout: 1000ms
  connect-timeout: 1000ms

expense-manager:
  url: "expense/manager/some/url"
  read-timeout: 1000ms
  connect-timeout: 1000ms

payment-manager:
  url: "expense/manager/some/url"
  read-timeout: 1000ms
  connect-timeout: 1000ms
