package pl.edu.agh.gem.internal.job

enum class ReconciliationJobState {
    STARTING,
    REDUCING_EVIDENT_SETTLEMENTS,
    REDUCING_ZERO_BALANCES,
    SELECT_ALGORITHM,
    APPLY_GREEDY_ALGORITHM,
    APPLY_SET_PARTITION_ALGORITHM,
    APPLY_MAX_DIFFERENCE_FIRST_ALGORITHM,
    SAVING,
    ERROR,
}
